# Generated by Django 3.1.3 on 2020-11-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201123_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
    ]
