# Generated by Django 3.1.3 on 2020-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20201114_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstaff',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
